QulightL = { }

-- general
	QulightL.option_general = "General"
	QulightL.option_general_uiscale = "Auto UI Scale"
	QulightL.option_general_multisample = "Multisample protection (clean 1px border)"
	QulightL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"
	QulightL.option_general_AutoRepair = "Auto Repair items"
	QulightL.option_general_AutoGreed = "Auto Greed"												
	QulightL.option_general_AutoDisenchant = "Auto Disenchant"	 								  		  
	QulightL.option_general_AutoDeclineDuels = "Auto Decline Duels"
	QulightL.option_general_AutoAcceptInvite = "Enable Auto-Invite (Friends and Guildmates)"	 
	QulightL.option_general_AutoRelease = "Enable Auto-Release in battleground"
	QulightL.option_general_BlizzardsErrorFrameHiding = "Hide spamming error at the middle of your screen" 
	-- Unitframes
	QulightL.option_unitframes = "Unit Frames"
	QulightL.option_unitframes_enable = "Enable Unit Frames"
 	QulightL.option_unitframes_HealFrames = "Raid Frames for Healer" 
	QulightL.option_unitframes_showIndicators = "Buffs Indicator on Heal Raid Frames " 
	QulightL.option_unitframes_showAuraWatch = "Show buffs in corners" 
	QulightL.option_unitframes_ShowParty = "Show party frames (shown as 5man raid)" 
	QulightL.option_unitframes_ShowRaid = "Show raid frames" 
	QulightL.option_unitframes_RaidShowSolo = "Show raid frames even when solo" 
	QulightL.option_unitframes_RaidShowAllGroups = "Show raid groups 6, 7 and 8 (more than 25man raid)" 
	QulightL.option_unitframes_enableDebuffHighlight = "Enable *dispelable* debuff highlight for raid frames" 
	QulightL.option_unitframes_showRaidDebuffs = "Enable important debuff icons to show on raid units" 
	QulightL.option_unitframes_showtot = "Show target of target frame" 
	QulightL.option_unitframes_showpet = "Show pet frame" 
	QulightL.option_unitframes_showfocus = "Show focus frame" 
	QulightL.option_unitframes_showfocustarget = "Show focus target frame" 
	QulightL.option_unitframes_showBossFrames = "Show boss frame" 
	QulightL.option_unitframes_TotemBars = "Show Totem Bars"
	QulightL.option_unitframes_MTFrames = "Show main tank frames" 
	QulightL.option_unitframes_ArenaFrames = "Show arena frame" 
	QulightL.option_unitframes_Reputationbar = "Show Reputation bar" 
	QulightL.option_unitframes_Experiencebar = "Show Experience bar" 
	QulightL.option_unitframes_showPlayerAuras = "use a custom player buffs/debuffs frame instead of Blizzard's default" 
	QulightL.option_unitframes_ThreatBar = "Show Threat bar"
	QulightL.option_unitframes_showPortrait = "Show Portrait on player and target frames"
	QulightL.option_unitframes_showRunebar = "Show DK rune bar"
	QulightL.option_unitframes_showHolybar = "Show Paladin HolyPower bar" 
	QulightL.option_unitframes_showEclipsebar = "Show druid Eclipse bar" 
	QulightL.option_unitframes_showShardbar = "Show Warlock SoulShard bar" 
	QulightL.option_unitframes_RCheckIcon = "Show raid check icon" 
	QulightL.option_unitframes_Castbars = "Use built-in castbars" 
	QulightL.option_unitframes_showLFDIcons = "Show dungeon role icons in raid/party" 
	--media
	QulightL.option_media = "Media" 	
	QulightL.option_media_font = "main font for Qulight UI" 
	QulightL.option_media_pxfont = "1 px font for Qulight UI" 
	QulightL.option_media_fontsize = "Size of font " 
	QulightL.option_media_bordercolor = "Border color" 
	QulightL.option_media_backdropcolor = "Background color" 
	QulightL.option_media_texture = "Texture" 
	QulightL.option_media_blank = "Background Texture" 
	--bags
	QulightL.option_bags = "Bags"	
	QulightL.option_bags_Enable = "Enable all in one bag"
	QulightL.option_bags_BagBars = "Enable bags panel"
	--datatext
	QulightL.option_datatext = "Data Text"
	QulightL.option_datatext_Durability = "Durability position (0 for disabled)"	
	QulightL.option_datatext_System = "Latency and FPS position (0 for disabled)"
	QulightL.option_datatext_Gold = "Gold position (0 for disabled)"
	QulightL.option_datatext_Guild = "Guild position (0 for disabled)"
	QulightL.option_datatext_Friends = "Friends position (0 for disabled)"
	QulightL.option_datatext_Bags = "Bags position (0 for disabled)"
	QulightL.option_datatext_Wowtime = "Time position (0 for disabled)"
	QulightL.option_datatext_Togglemenu = "ToggleMenu"
	QulightL.option_datatext_Time24 = "Enable 24h time"
	QulightL.option_datatext_Localtime = "Use Local Time instead of Server Time"
	QulightL.option_datatext_classcolor = "Class color data text"
	QulightL.option_datatext_color = "If Class color data text false then choose color: "
	--loot
	QulightL.option_loot = "Loot"
	QulightL.option_loot_lootframe = "Enable loot window"
	QulightL.option_loot_rolllootframe = "Enable item roll window"
	QulightL.option_loot_position = "Позиция окна розыгрыша"
	--misk
	QulightL.option_enable = "Enable" 
	QulightL.option_addonmanager = "Addon Manager" 
	QulightL.option_togglemenu = "Toggle menu" 
	QulightL.option_togglemenu_buttonwidth = "Button width" 
	QulightL.option_togglemenu_buttonheight = "Button height" 
	QulightL.option_togglemenu_classcolor = "Classcolor border" 
	QulightL.option_classtimer = "Class Timer" 
	QulightL.option_cooldown = "cooldown" 
	QulightL.option_skinframe = "Skinframe" 	
	QulightL.option_filger = "Filger" 
	--chat
	QulightL.option_chat = "Chat"
	QulightL.option_chat_enable = "Enable"
	QulightL.option_chat_chatbar= "Enable chat bar" 
	QulightL.option_chat_chatframewidth = "Chat width"
	QulightL.option_chat_chatframeheight = "Chat height"
	QulightL.option_chat_editboxwidth = "Editbox width"
	QulightL.option_chat_editboxheight = "Editbox height"
	QulightL.option_chat_tabtextcolor = "Tab text color"
	QulightL.option_chat_ChatFrame = "Позиция чата"
    --buffs
	QulightL.option_buffs = "Buffs/Debuffs"
	QulightL.option_buffs_enable = "Enable"
	QulightL.option_buffs_iconsize = "Buffs size"
	QulightL.option_buffs_iconsizede = "Debuffs size"
	QulightL.option_buffs_timefontsize = "Time font size"
	QulightL.option_buffs_countfontsize = "Count font size" 
	QulightL.option_buffs_spacing = "Buffs spacing" 
	QulightL.option_buffs_debuffspacing = "Debuffs spacing" 
	QulightL.option_buffs_timeYoffset = "timeYoffset" 
	QulightL.option_buffs_BUFFS_PER_ROW = "Buffs per row" 
	QulightL.option_buffs_BUFFpos = "Buffs positions" 
	QulightL.option_buffs_DEBUFFpos = "Debuffs positions" 
	--addonskinning
	QulightL.option_addonsskins = "Addon Skins"
	QulightL.option_addonsskins_DBM = "DBM(/dbmskin apply)"
	QulightL.option_addonsskins_PallyPower = "PallyPower" 
	QulightL.option_addonsskins_Skada = "Skada" 
	QulightL.option_addonsskins_Recount = "Recount"
	QulightL.option_addonsskins_Omen = "Omen"
	QulightL.option_addonsskins_KLE = "KLE"	
	QulightL.option_addonsskins_Quartz = "Quartz"		
	QulightL.option_addonsskins_Bigwigs = "Bigwigs(/bigwigstest apply)"
	--nameplates
	QulightL.option_nameplates = "Nameplates"
	QulightL.option_nameplates_enable  = "Enable Nameplates"
	QulightL.option_nameplates_hpHeight  = "HP Height"
	QulightL.option_nameplates_hpWidth  = "HP Width"
	QulightL.option_nameplates_cbIconSize  = "Castbar icon size"
	QulightL.option_nameplates_cbHeight = "Castbar Height"
	QulightL.option_nameplates_cbWidth  = "Castbar Width"

	QulightL.option_Minimap = "Minimap"
	QulightL.option_Minimapenable = "Enable"
	QulightL.option_Minimapminimapsize = "Minimap size"
	QulightL.option_Map = "Map"
	QulightL.option_mapenable = "Enable"
	
	QulightL.option_markbar = "Mark bar"
	QulightL.option_markbarenable = "Enable mark bar"
	
	-- tooltip
	QulightL.option_tooltip = "Tooltip"
	QulightL.option_tooltip_enable = "Enable tooltip"
	QulightL.option_tooltip_hidecombat = "Hide tooltip in combat"
	QulightL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
	QulightL.option_tooltip_hideuf = "Hide tooltip on unit frames"
	QulightL.option_tooltip_cursor = "Enable cursor tooltip"
	
	
	QulightL.option_Actionbars = "Action Bars"
	QulightL.option_Actionbars_enable = "Enable Action Bars"
	QulightL.option_Actionbars_hotkey = "Show hotkey on buttons"
	QulightL.option_Actionbars_shapeshiftmouseover = "Shapeshift bar or Totem bar on mouseover"
	QulightL.option_Actionbars_hideshapeshift = "Hide Shapeshift bar or Totem bar"
	QulightL.option_Actionbars_bottomrows = "numbers of row you want to show at the bottom (select between 1-3 only)"
	QulightL.option_Actionbars_rightbars = "numbers of right bar you want (0,2 only)"
	QulightL.option_Actionbars_splitbar = "split the third right actionbar into two rows of 3 on the left and right side of the main actionbar"
	QulightL.option_Actionbars_rightbarmouseover = "enable right bars and pet bar on mouse over"
	QulightL.option_Actionbars_buttonsize = "Size of the main action buttons"
	QulightL.option_Actionbars_buttonspacing = "Spacing of the main action buttons"
	QulightL.option_Actionbars_petbuttonsize = "Size of the pet/stance action buttons"
	QulightL.option_Actionbars_petbuttonspacing = "Spacing of the pet buttons"
	QulightL.option_Actionbars_swaptopbottombar = "Swap the top and bottom actionbar positions"
	QulightL.option_Actionbars_macrotext = "Display macro text on actionbuttons"
	QulightL.option_Actionbars_verticalstance = "Vertical Stance Bar"
	QulightL.option_Actionbars_microbar = "Display MicroBar"
	QulightL.option_Actionbars_mousemicro = "MicroBar on mouseover"
	
	QulightL.option_misk = "Other"
	QulightL.option_raidutility = "Raid Utility"
	QulightL.option_BuffReminderRaidBuffs = "Reminder Raid Buffs"
	QulightL.option_Reminder = "Reminder Solo Buffs"
	
	
	
	QulightL.option_reset = "Reset"
	QulightL.option_apply = "Apply"
	QulightL.option_close = "Close"
	QulightL.option_setsavedsetttings = "Set settings Per-Character"
	QulightL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	QulightL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	QulightL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	QulightL.option_makeselection = "You must make a selection before you can continue to config."