if GetLocale() == "ruRU" then
	-- general
	QulightL.option_general = "Общее"
	QulightL.option_general_uiscale = "Автоматически масштабировать интерфейс"
	QulightL.option_general_override = "Использовать раскладку для высокого разрешения при низком разрешении"
	QulightL.option_general_multisample = "Ровные края шириной 1 пиксель"
	QulightL.option_general_customuiscale = "Масштаб интерфейса (если автомасштабирование отключено)"
	QulightL.option_general_AutoRepair = "Автоматическая починка"
	QulightL.option_general_AutoGreed = "Автоматический Greed от зеленых вещей"												
	QulightL.option_general_AutoDisenchant = "Автоматический Disenchant на синьку/зеленку"	 								  		  
	QulightL.option_general_AutoDeclineDuels = "Автоматический отказ от дуэлей"	
	QulightL.option_general_AutoAcceptInvite = "Автоматический приём инвайта от друзей/гильдии"	 
	QulightL.option_general_AutoRelease = "Автоматическое воскрешение на БГ/ОЛО"	 
	QulightL.option_general_BlizzardsErrorFrameHiding = "Прятать сообщения об ошибках посреди экрана"	 
	-- Unitframes
	QulightL.option_unitframes = "Юнитфреймы"
	QulightL.option_unitframes_enable = "Включить рамки юнитов"
 	QulightL.option_unitframes_HealFrames = "Хил рейд фреймы" 
	QulightL.option_unitframes_showIndicators = "Индикаторы бафов для хил рейд фреймов" 
	QulightL.option_unitframes_showAuraWatch = "Таймеры хотов/щитов для хил рейд фреймов" 
	QulightL.option_unitframes_ShowParty = "Отображение пати в стиле рейд фреймов" 
	QulightL.option_unitframes_ShowRaid = "Включить рейд фреймы" 
	QulightL.option_unitframes_RaidShowSolo = "Включить рейд фреймы в соло" 
	QulightL.option_unitframes_RaidShowAllGroups = "Включить 6.7.8 группу в рейде" 
	QulightL.option_unitframes_enableDebuffHighlight = "Светохуйня на рейд фреймах" 
	QulightL.option_unitframes_showRaidDebuffs = "Отображение рейд дебафов" 
	QulightL.option_unitframes_showtot = "Включить цель цели" 
	QulightL.option_unitframes_showpet = "Включить пет фрейм" 
	QulightL.option_unitframes_showfocus = "Включить фокус фрейм" 
	QulightL.option_unitframes_showfocustarget = "Включить цель фокуса" 
	QulightL.option_unitframes_showBossFrames = "Включить босс фреймы" 
	QulightL.option_unitframes_TotemBars = "Включить панель тотемов для Шаманов"
	QulightL.option_unitframes_MTFrames = "Включить панели главных танков" 
	QulightL.option_unitframes_ArenaFrames = "Включить арена фреймы" 
	QulightL.option_unitframes_Reputationbar = "Включить полоску репутации" 
	QulightL.option_unitframes_Experiencebar = "Включить полоску опыта" 
	QulightL.option_unitframes_showPlayerAuras = "Использовать стандартные близз бафы/дебафы" 
	QulightL.option_unitframes_ThreatBar = "Включить полосу угрозы"
	QulightL.option_unitframes_showPortrait = "Отображать портрет на плеер и таргет фрейме"
	QulightL.option_unitframes_showRunebar = "Включить панель рун для Рыцарей Смерти"
	QulightL.option_unitframes_showHolybar = "Включить холи панель для Паладинов" 
	QulightL.option_unitframes_showEclipsebar = "Включить экслипс панель для Баланс Друидов" 
	QulightL.option_unitframes_showShardbar = "Включить панель для шардов для Варлоков" 
	QulightL.option_unitframes_RCheckIcon = "Включить иконки Готовности на рейд фреймах" 
	QulightL.option_unitframes_Castbars = "Включить кастбары" 
	QulightL.option_unitframes_showLFDIcons = "Включить лфг иконки" 
	--media
	QulightL.option_media = "Media" 	
	QulightL.option_media_font = "Основной шрифт для Qulight UI" 
	QulightL.option_media_pxfont = "1 px шрифт для Qulight UI" 
	QulightL.option_media_fontsize = "Размер шрифта" 
	QulightL.option_media_bordercolor = "Цвет бордюров" 
	QulightL.option_media_backdropcolor = "Цвет фона" 
	QulightL.option_media_texture = "Тектура для полосок" 
	QulightL.option_media_blank = "Текстура для фона" 
	--bags
	QulightL.option_bags = "Cумки"	
	QulightL.option_bags_Enable = "Включить сумки"
	QulightL.option_bags_BagBars = "Включить панель сумок"
	--datatext
	QulightL.option_datatext = "Текст панелей"
	QulightL.option_datatext_Durability = "Прочность"
	QulightL.option_datatext_System = "Память/ФПС/Пинг"
	QulightL.option_datatext_Gold = "Золото"
	QulightL.option_datatext_Guild = "Гильдия"
	QulightL.option_datatext_Friends = "Друзья"
	QulightL.option_datatext_Bags = "Сумки"
	QulightL.option_datatext_Wowtime = "Время"
	QulightL.option_datatext_Togglemenu = "МиниМеню"
	QulightL.option_datatext_Time24 = "24-часовой формат времени"
	QulightL.option_datatext_Localtime = "Использовать локальное время вместо серверного"
	QulightL.option_datatext_classcolor = "Включить цвет текста под цвет класса"
	QulightL.option_datatext_color = "Если цвет текста под цвет класса выключен, то выберите цвет:"
	--loot
	QulightL.option_loot = "Лут"
	QulightL.option_loot_lootframe = "Включить окно добычи"
	QulightL.option_loot_rolllootframe = "Включить окно розыгрыша"
	QulightL.option_loot_position = "Позиция окна розыгрыша"
	--misk
	QulightL.option_enable = "Включить" 
	QulightL.option_addonmanager = "Аддон менеджер" 
	QulightL.option_togglemenu = "МиниМеню" 
	QulightL.option_togglemenu_buttonwidth = "Ширина кнопок" 
	QulightL.option_togglemenu_buttonheight = "Высота кнопок" 
	QulightL.option_togglemenu_classcolor = "Включить рамки под цвет класса" 
	QulightL.option_classtimer = "КлассТаймер" 
	QulightL.option_cooldown = "Кулдауны" 
	QulightL.option_skinframe = "Близскин" 	
	QulightL.option_filger = "Филгер" 
	--chat
	QulightL.option_chat = "Чат"
	QulightL.option_chat_enable = "Включить"
	QulightL.option_chat_chatbar= "Включить чат бар(кнопки для каналов)" 
	QulightL.option_chat_chatframewidth = "Ширина чата"
	QulightL.option_chat_chatframeheight = "Высота чата"
	QulightL.option_chat_editboxwidth = "Ширина поля ввода текста"
	QulightL.option_chat_editboxheight = "Высота поля ввода текста"
	QulightL.option_chat_tabtextcolor = "Цвет закладок чата"
	QulightL.option_chat_ChatFrame = "Позиция чата"
    --buffs
	QulightL.option_buffs = "Бафы/Дебафы"
	QulightL.option_buffs_enable = "Включить"
	QulightL.option_buffs_iconsize = "Размер бафов"
	QulightL.option_buffs_iconsizede = "Размер дебафов"
	QulightL.option_buffs_timefontsize = "Размер шрифта времени"
	QulightL.option_buffs_countfontsize = "Размер шрифта стаков" 
	QulightL.option_buffs_spacing = "Интервал между бафами" 
	QulightL.option_buffs_debuffspacing = "Интервал между дебафами" 
	QulightL.option_buffs_timeYoffset = "Отступ по вертикали" 
	QulightL.option_buffs_BUFFS_PER_ROW = "Количество бафов в ряду" 
	--addonskinning
	QulightL.option_addonsskins = "Скининг Аддонов"
	QulightL.option_addonsskins_DBM = "DBM(/dbmskin apply)"
	QulightL.option_addonsskins_PallyPower = "PallyPower" 
	QulightL.option_addonsskins_Skada = "Skada" 
	QulightL.option_addonsskins_Recount = "Recount"
	QulightL.option_addonsskins_Omen = "Omen"
	QulightL.option_addonsskins_KLE = "KLE"	
	QulightL.option_addonsskins_Quartz = "Quartz"		
	QulightL.option_addonsskins_Bigwigs = "Bigwigs(/bigwigstest apply)"
	--nameplates
	QulightL.option_nameplates = "Неймплейты"
	QulightL.option_nameplates_enable  = "Включить индикаторы здоровья"
	QulightL.option_nameplates_hpHeight  = "Высота индикатора здоровья"
	QulightL.option_nameplates_hpWidth  = "Ширина индикатора здоровья"
	QulightL.option_nameplates_cbIconSize  = "Размер иконки у кастбара"
	QulightL.option_nameplates_cbHeight = "Высота кастбара"
	QulightL.option_nameplates_cbWidth  = "Ширина кастбара"

	QulightL.option_Minimap = "Минимапа"
	QulightL.option_Minimapenable = "Включить"
	QulightL.option_Minimapminimapsize = "Размер Минимапы"
	QulightL.option_Map = "Карта"
	QulightL.option_mapenable = "Включить"
		
	QulightL.option_tooltip = "Тултип"
	QulightL.option_tooltip_enable = "Включить подсказку"
	QulightL.option_tooltip_hidecombat = "Прятать подсказку в бою"
	QulightL.option_tooltip_hidebuttons = "Прятать подсказку для кнопок панели действий"
	QulightL.option_tooltip_hideuf = "Прятать подсказку для рамок юнитов"
	QulightL.option_tooltip_cursor = "Подсказка под указателем мыши"
		
	QulightL.option_markbar = "Панель меток"
	QulightL.option_markbarenable = "Включить панель меток"
	
	QulightL.option_Actionbars = "Панели команд"
	QulightL.option_Actionbars_enable = "Включить панели комманд"
	QulightL.option_Actionbars_hotkey = "Показывать горячие клавиши на кнопках"
	QulightL.option_Actionbars_shapeshiftmouseover = "Показывать панель стоек/тотемов при наведении мыши"
	QulightL.option_Actionbars_hideshapeshift = "Прятать панель стоек или тотемов"
	QulightL.option_Actionbars_bottomrows = "Количество панелей комманд снизу (1 - 3)"
	QulightL.option_Actionbars_rightbars = "Количество панелей комманд справа (0 или 2)"
	QulightL.option_Actionbars_splitbar = "Панели слева и справа от главной панели"
	QulightL.option_Actionbars_rightbarmouseover = "Отображать кнопки справо и пет бар только по наведению мышки"
	QulightL.option_Actionbars_buttonsize = "Размер кнопок панели действий"
	QulightL.option_Actionbars_buttonspacing = "Промежуток между кнопками панели действий"
	QulightL.option_Actionbars_petbuttonsize = "Размер кнопок панели действий для питомца/стоек"
	QulightL.option_Actionbars_petbuttonspacing = "Интервал между кнопками у пет бара"
	QulightL.option_Actionbars_swaptopbottombar = "Поменять 1 и 2 панели местами"
	QulightL.option_Actionbars_macrotext = "Показывать название макро на кнопоках"
	QulightL.option_Actionbars_verticalstance = "Расположить панель стоек вертикально"
	QulightL.option_Actionbars_microbar = "Включить микроменю"
	QulightL.option_Actionbars_mousemicro = "Показывать микроменю при наведении курсора"
	
	QulightL.option_misk = "Разное"
	QulightL.option_raidutility = "Утилиты для рейда"
	QulightL.option_BuffReminderRaidBuffs = "Панель рейд бафов на игроке(Напоминалка)"
	QulightL.option_Reminder = "Панель соло бафов на игроке(Напоминалка)"
	
	
	
	QulightL.option_reset = "Сбросить"
	QulightL.option_apply = "Применить"
	QulightL.option_close = "Закрыть"
	QulightL.option_setsavedsetttings = "Установить настройки для персонажа"
	QulightL.option_resetchar = "Вы уверены, что хотите сбросить все настройки для персонажа до настроек по умолчанию?"
	QulightL.option_resetall = "Вы уверены, что хотите сбросить все настройки?"
	QulightL.option_perchar = "Вы уверены что хотите сменить режим сохранения настроек?"
	QulightL.option_makeselection = "Вы должны сделать выбор прежде чем продолжите конфигурацию"
end